### ISSUE TITLE
AccessViolationException when Temp path contains "á"

### ISSUE THREAD

**Issue by NickeManarin** [jhabjan/Ghostscript.NET#39]
Whenever the **TEMP**/**TMP** ambient variables contains a character with the [(´) diacritic](https://en.wikipedia.org/wiki/Acute_accent), **GhostScript.NET** can't access the temp folder.

The user had both **TEMP** and **TMP** variables with:
    `%USERPROFILE%\AppData\Local\Temp`
Which results in:
    `C:\Users\Usuário\AppData\Local\Temp`

Changing the location to something else, like `C:\AppData\Local\Temp` solves this issue, but it's not the best solution.

This is the stack trace, abridged:

```
System.AccessViolationException 

at Ghostscript.NET.Interpreter.GhostscriptInterpreter.Dispose(Boolean) 
at Ghostscript.NET.Viewer.GhostscriptViewer.Close() 
at Ghostscript.NET.Viewer.GhostscriptViewer.Open(System.String, 
   Ghostscript.NET.GhostscriptVersionInfo, Boolean) 
at MyProject.PdfPrintViewer.EndInit() 
```

**Comment by NickeManarin** [comment]
I'm not sure about other diacritics, because I didn't test it enough.

**Comment by Crayjin** [comment]
Commit https://github.com/jhabjan/Ghostscript.NET/commit/280268c710427f0180e20f06bdabd3a1a01debcb could have fixed that issue as well. Could you check that again?

**Comment by NickeManarin** [comment]
It works. Thank you.

**Comment by soofian** [comment]
I am calling Ghostscript.NET in ASP.NET thread and continuously getting this exception found in event viewer of my server machine:

Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at Ghostscript.NET.Interpreter.GhostscriptInterpreter.InitArgs(System.String[])
   at Ghostscript.NET.Viewer.GhostscriptViewer.Open()
   at Ghostscript.NET.Rasterizer.GhostscriptRasterizer.Open(System.String, Ghostscript.NET.GhostscriptVersionInfo, Boolean)

I am using latest Ghostscript.NET. Any fix please ?

**Comment by Rbn3D** [comment]
I'm still suffering a similar issue (using latest version 1.2.1):
This is the exception error message while trying to generate a PDF's thumbnail:
´´´
IO error for file: 'C:\Users\Test_acc�nted_path\Filename.pdf'
´´´
The path looks like this: 'C:\Users\Test_accénted_path\Filename.pdf'

If I use an unaccented path, it works.

**Comment by Rbn3D** [comment]
Looks like it's fixed in https://github.com/jhabjan/Ghostscript.NET/commit/280268c710427f0180e20f06bdabd3a1a01debcb , but still no NuGet release... I would appreciate a new nuget version.
