### ISSUE TITLE
Pdf to image issue

### ISSUE THREAD

**Issue by fabiencomte** [jhabjan/Ghostscript.NET#48]
Hello,
When i render a pdf page containing text and schematics to an image, the text looks correct but the schematics have a black background (original is white).

Do you have an idea please ?

**Comment by evilduckz** [comment]
I was able to replicate this as well. doing a pdf to tiff with the rasterizer. The pdf contained a signature (using fill and sign) and upon conversion the tiff had a black box where the signature should have been. I did some additional research and the problem lies within the viewer. Soon as i open the pdf  with the viewer (no conversion) the signature appears with a infilled black rectangle.

**Comment by fabiencomte** [comment]
Hello, 
Could you give me your command please to do some tests ?

**Comment by evilduckz** [comment]
the easiest way to replicate this issue is to sign a pdf (using fill and sign) and then open it with the ghostscript.net viewer. The problem exists in the viewer anyways since that is the code the rasterizer uses. Please let me know if you need additional details.

**Comment by fabiencomte** [comment]
For you, the bug is in the viewer, right ?

**Comment by evilduckz** [comment]
If you run the ghostscript.net viewer the bug will present it self by opening a pdf that has a signature in it via a fill and sign

**Comment by Cabecinha84** [comment]
Hello,

I have found the same problem you have reported. pdf`s with signatures, look with black backgorund and colors wrong on the sign box.
I have tried debbuging ghostscript.net viewer but couldn`t find the ghostscript parameter that is missing or wrong that is causing this.
Did you find a solution using ghostscript.net?

Thank you.

**Comment by fabiencomte** [comment]
Hello,

No I have no solution, sorry…

**Comment by jhabjan** [comment]
Fixed in today's v.1.2.2. release.
