### ISSUE TITLE
can we deploy this to azure?

### ISSUE THREAD

**Issue by alexgman** [jhabjan/Ghostscript.NET#70]
I'd like to be able to convert a multipage pdf to a multipage tiff within an Azure Function, can we deploy this to azure?

**Comment by euangordon** [comment]
Hi @alexgman it is possible but requires some fun and games so that it works locally and in the deployed environment.

Firstly, you need to get the two DLLs, and add them to your project, make sure you set "Copy to Output Directory" to "Copy always" as shown:

![image](https://user-images.githubusercontent.com/32622054/91425010-7bc9b380-e852-11ea-96e2-c602be27658e.png)

Next up, in your Azure Function, Run method you need to get the ExecutionContext:

`public static void Run([TimerTrigger("0 0 * * * *")] TimerInfo myTimer, TraceWriter log, ExecutionContext context)`

Use this to find the Root Application Path:

`string rootApplicationPath = Path.GetFullPath(Path.Combine(context.FunctionDirectory, @"..\"));`

Now you can load in the DLLs:

`        
public static void LoadNativeAssemblies(string rootApplicationPath)
        {
            string newPath = Path.GetFullPath(Path.Combine(rootApplicationPath, @"dll\"));
            string gsDllPath = Path.Combine(newPath, Environment.Is64BitProcess ? @"gsdll64.dll" : @"gsdll32.dll");

            if (!File.Exists(gsDllPath))
            {
                Log.Error($"The library {gsDllPath} required to run this program is not present!");
                throw new FileLoadException($"The library {gsDllPath} required to run this program is not present!");
            }

            _version = new GhostscriptVersionInfo(new Version(0, 0, 0), gsDllPath, string.Empty, GhostscriptLicense.GPL);
        }
`
Now the GhostScript DLLs are loaded and you can use it in your Azure Function. 

Example, I am using it to create thumb nails:

`                    public static MemoryStream GetPDFThumbnailStream(Stream PdfStream, int Dpi)
        {
            PdfStream.Position = 0;

            var imageStream = new MemoryStream();

            using (var rasterizer = new GhostscriptRasterizer())
            {
                rasterizer.Open(PdfStream, _version, true);

                Image img = rasterizer.GetPage(Dpi, Dpi, 1);
                img.Save(imageStream, ImageFormat.Jpeg);
                imageStream.Position = 0;

                return imageStream;
            }
        }`
